# ============================= Configuraciones de SwayFX ===================================

# Configuraciones exclusivas de SwayFX / SwayFX config only
# Descomentar en caso de usar el Sway normal / uncomment if you use the regular Sway

blur enable
blur_passes 3
blur_radius 5
blur_noise 0

corner_radius 6

blur_xray disable

# Waybar blur

layer_effects "waybar" {
    blur enable;
    blur_xray enable;
    blur_ignore_transparent enable;
    shadows enable;
}


# Unfocused window
default_dim_inactive 0
scratchpad_minimize enable
