
# ===================================== Floating apps =======================================

# Apps que prefiero que se ejecuten por defecto en modo flotante
# Apps that I prefer to excecute in floating mode

for_window [app_id=org.pulseaudio.pavucontrol] floating enable
for_window [app_id=org.kde.kdeconnect.app] floating enable
for_window [app_id=blueman-manager] floating enable
for_window [app_id=nm-connection-editor] floating enable
for_window [app_id=org.gnome.Calculator] floating enable
for_window [app_id=org.gnome.Nautilus] floating enable
for_window [app_id=imv] floating enable
for_window [app_id=io.github.alainm23.planify] floating enable

# ===========================================================================================
