# ============================= Configuracion de Hardware ===================================

# Estos ajustes fueron hechos especificamente para mi laptop: Lenovo Thinkpad T495s,
# obligatorio cambiarlos segun tu equipo

# The next settings were made for specifically for mi laptop: Lenovo Thinkpad T495s,
# you must change it according to your device
#
input "type:mouse" {
    click_method button_areas
    pointer_accel 0
}

input "type:pointer" {
    middle_emulation disabled
}

input "2:14:ETPS/2_Elantech_TrackPoint" {
    dwt enabled
    pointer_accel -0.4
    scroll_factor 0.2
    scroll_method on_button_down
    middle_emulation disabled
}

input "type:touchpad" {
    tap enabled
    natural_scroll true
    click_method clickfinger
    middle_emulation disabled
    pointer_accel 0.1
    drag_lock disabled
}

input type:keyboard {
    xkb_layout "us"
    xkb_rules "evdev"
    xkb_variant "altgr-intl"
}


# Disable paste with the middle click
#bindsym --whole-window button2 exec head -c 1 /dev/null


# ===========================================================================================
